Fixed apparent pass (green) regardles of fails in os matrix.

diff --git a/.github/workflows/ansible-install.yml b/.github/workflows/ansible-install.yml
--- a/.github/workflows/ansible-install.yml
+++ b/.github/workflows/ansible-install.yml
@@ -6,7 +6,7 @@ on:
 jobs:
   install-seek-from-ansible:
     runs-on: ${{matrix.os}}
-    #continue-on-error: true
+    continue-on-error: true
     strategy:
       matrix:
         os: [ubuntu-18.04,ubuntu-20.04,ubuntu-22.04]
@@ -69,3 +69,17 @@ jobs:
         working-directory: /home/runner/work/SEEK
         run: |
           bash -lc 'bundle exec rails test test/functional'
+
+
+  fail-on-any-os:
+    # Without this step workflow remains "green" regardles of fails above.
+    name: Workflow Status
+    needs:
+      - install-seek-from-ansible
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - uses: technote-space/workflow-conclusion-action@v3.0.3
+      - name: Check Job Status status and fail if they are red
+        if: env.WORKFLOW_CONCLUSION == 'failure'
+        run: exit 1
